### ISSUE TITLE
ReviewBot: add_review() failure should cause crash and be able to pickup later

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#1050]
Eg. https://build.opensuse.org/request/show/514577 and https://build.opensuse.org/request/show/511736

review team group doesn't added on it, thus it does not pass human review actually.

due to https://github.com/openSUSE/osc-plugin-factory/blob/master/check_source.py#L121

**Comment by darix** [comment]
this let slip through changes entries which didn't comply with our policy.

**Comment by lnussel** [comment]
https://github.com/openSUSE/osc-plugin-factory/blob/master/check_source.py#L121

**Comment by jberry-suse** [comment]
The diff related rules were carried over during port and can be seen below.
https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/source-checker.pl#L287-L315

Based on those rules I would have expected the bot to have requested human review. It looks like OBS failed to handle the review request and crashed. I tried to check the log, but unfortunately the packagelist logs do not go back far enough. I do however see other `HTTP Error 503: Service Unavailable` errors and it definitely within the realm of possibility.

As I guessed after see this report the reviews are confirmed to be added before accepting the original review. What likely occurred:

- `add_review(review_team)` (OBS went caboom)
- `add_review(repo_checker)`
- `_set_review(factoryauto, accepted)`

`ReviewBot.add_review()` catches HTTP errors:

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/ReviewBot.py#L211-L215

While `CheckSource` does not handle the `False` return value.

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/check_source.py#L120-L132

I would like to see this in the logs, but this seems to be the only logical explanation.

The desired behavior should likely be to optionally add retry logic to `add_review` and handle a failure at the `ReviewBot` layer as this `add_review()` method is called by a variety of bots without checking the return value. There seems to be two possible approaches:

- do not catch the exception so the bot crashes and will retry the same review again later
- internally note the failure in `ReviewBot` and  as such do not update the review for that request

One issue with either approach is that if the ultimate result is failure the `add_review()` method does not check if the review has already been added, although that logic exists elsewhere (like leaper). There is a comment above the `add_review()` method that would need to be investigated.

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/ReviewBot.py#L190-L191

Otherwise, it would seem to make more sense to check if review already added and skip so the bot could just pick back up where it left off next time it runs.

The overall goal being to make the "result" of a review be atomic in that all the desired changes are made or the bot stops and picks up later.

The general design of the bots seems to be to crash and try again later or complete. As such I think `ReviewBot` should simply not catch the exception. There are other calls like:

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/check_source.py#L128

That should also constitute a crash and would not be handled by `ReviewBot`. If we go with this approach then `add_review()` should be altered to handle picking up where the bot left off.

**Comment by jberry-suse** [comment]
The relevant logic in `leaper`:

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/leaper.py#L454-L467

**Comment by jberry-suse** [comment]
The logic exists in a few places, some bots check sometimes and not others. It does not seem correct to fail the review because a review could not be added. If the bot somehow **cannot** add the review that is a should not be the fault of the request.

**Comment by jberry-suse** [comment]
The seeming reason for not checking duplicates:

https://github.com/openSUSE/osc-plugin-factory/blob/1cefbfce343b280ea1e9db2af5b06a0382502582/ReviewBot.py#L174-L175

**Comment by jberry-suse** [comment]
To be clear we may also want to adjust the diffcount algorithm.

**Comment by jberry-suse** [comment]
Actually seeing other requests seemingly in same state as a local run wants to add the review team.

- https://build.opensuse.org/request/show/515264
- https://build.opensuse.org/request/show/515277

Those are in the log, but show no HTTP error.

**Comment by darix** [comment]
you still need to kill this code https://github.com/openSUSE/osc-plugin-factory/blob/master/check_source.py#L121

**Comment by jberry-suse** [comment]
As noted that did not apply to the cases indicated so I fixed the problem that did. If we want to change that bit someone should have responded to my inquiry. Drop the diff check entirely? If so I'll drop that old algorithm from the perl script as well.

**Comment by darix** [comment]
yes that code should be gone as well.

**Comment by jberry-suse** [comment]
Now if only someone could spend 5 minutes and deploy the TW snapshots before another 8 months go bye. Perhaps I should start responding as quickly.
