### ISSUE TITLE
repo-checker: too frequent need for staging rebase

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#1067]
Current sample, Staging:J

this morning, it 'only' complained about 'packages uninstallable' (this is an issue on it's own, as it's also not true) - after a checkin round (cntaining imagemagic(k) it now also contains file conflicts between the image magick in oS:F and the one still build in Staging. 

Rebasing all 13 stagings all the time for such changes sounds unrealsitic, an immense waste of resources and ultimately slows down the TW process much more than is beneficial.

Imho, file conflicts should only be reported as an issue if they are based on packages inside the staging project

**Comment by DimStar77** [comment]
specifically it's about this part in :J's comment section:

```
found conflict of libMagickCore-7_Q16HDRI2-7.0.6.0-4.4.x86_64 with libMagickCore-7_Q16HDRI3-7.0.6.7-1.1.x86_64:
  - /usr/lib64/ImageMagick-7.0.6/modules-Q16HDRI/coders/aai.la
  - /usr/lib64/ImageMagick-7.0.6/modules-Q16HDRI/coders/aai.so
```

**Comment by jberry-suse** [comment]
This was due to the hotfix for the renamed sub-packages that had issues problem we saw yesterday. Reverting the changed resolved the majority of problems. I went ahead and reworked some things to resolve the rest and will write up a report tomorrow as this was quite some speed coding.

Suffice it to say, the original reason for this issue has been resolved, but the general topic of rebasing frequency may need to be re-opened depending on observations going forward. I had an issue I created previous where I noted the changes that may require more frequent rebasing.
