### ISSUE TITLE
staging config should come from attribute

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#1104]
For SLE there are so many staging managers, it's no longer funny. And with the no-cleanup-list being so important for the health, it's quite important that they all share the config.

As such: please support some attribute in $PRJ:Staging that the config is taking from.

**Comment by jberry-suse** [comment]
Presumably you are referring to a piece of config that can be updated outside of the code, but shared. I already implemented such a feature which I refer to as the remote config. https://github.com/openSUSE/osc-plugin-factory/blob/ed70089adfa3acdd77e447460f4d903f992d2dcb/osclib/conf.py#L165-L179

For an example, see [Factory remote config](https://build.opensuse.org/package/view_file/openSUSE:Factory:Staging/dashboard/config).

The conflg is applied on top of the existing config and will thus override any prior options. It also follows the same formatting and parsing rules as `.oscrc`.

Since SLE has previously not utilize a dashboard container the feature was disabled, but it can be enabled easily.

**Comment by jberry-suse** [comment]
Assuming the dashboard is properly owned my staging masters they should all be able to edit. Just get the sum of current config in there and then have everyone remote their local overrides.
