### ISSUE TITLE
repo_checker: excessive cache file

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#1265]
Just found that ~/.cache/opensuse-repo-checker/_builddepinfo was 63GB, making repochecker block in D all the time. Do we need the _buildepinfo persistent on disk?

**Comment by jberry-suse** [comment]
Umm, that sounds very wrong. Something else going on. That is requested each time it does a cycle check. Assuming you are talking about multiple files as they are never that big on my system.

**Comment by jberry-suse** [comment]
To be clear, not doubting that is caches, but one OBS request returning 63GB? that would be problem enough.

**Comment by lnussel** [comment]
After one day the file is 18GB already

**Comment by lnussel** [comment]
# du -sh /home/osrt-repo-checker/.cache/opensuse-repo-checker/_builddepinfo
18G     /home/osrt-repo-checker/.cache/opensuse-repo-checker/_builddepinfo
# file /home/osrt-repo-checker/.cache/opensuse-repo-checker/_builddepinfo
/home/osrt-repo-checker/.cache/opensuse-repo-checker/_builddepinfo: Berkeley DB (Hash, version 9, native byte-order)

**Comment by lnussel** [comment]
# db_stat -d /home/osrt-repo-checker/.cache/opensuse-repo-checker/_builddepinfo -f
Tue Nov 21 09:56:54 2017        Local time
61561   Hash magic number
9       Hash version number
Little-endian   Byte order
        Flags
4589697 Number of pages in the database
4096    Underlying database page size
0       Specified fill factor
849     Number of keys in the database
849     Number of data items in the database
27      Number of hash buckets
0       Number of bytes free on bucket pages (100% ff)
0       Number of overflow pages
0       Number of bytes free in overflow pages (0% ff)
0       Number of bucket overflow pages
0       Number of bytes free in bucket overflow pages (0% ff)
0       Number of duplicate pages
0       Number of bytes free in duplicate pages (0% ff)
0       Number of pages on the free list

**Comment by jberry-suse** [comment]
As discussed with @lnussel in IRC last week this is due to the cycles code:

https://github.com/openSUSE/osc-plugin-factory/blob/60cdcec090374af8f39002f60210b9ff505f4cdc/osclib/cycle.py#L153-L162

During my refactoring of cycles code for new `repo-checker` it now loads cycle information directly from staging projects, and Leap 15.0 was recently enabled, the end result is a lot more results cached.

The temporary solution is to disable entirely, but a proper one seems like only caching the target project results since those are the only that are loaded multiple times in a single run.

**Comment by lnussel** [comment]
we need a fix for this, the hot fix will not survive :)

**Comment by jberry-suse** [comment]
Of course, a catching up on everything from before hackweek stacked on top of Thanksgiving holidays.
