### ISSUE TITLE
repo checker comments every hour

### ISSUE THREAD

**Issue by coolo** [openSUSE/osc-plugin-factory#1296]
I submitted some packages that ended on 5pm in openSUSE:Factory:Staging:adi:104 - since then I received mail from repo checker about file conflicts on 6pm, 7pm, ... it's 7am now and I'm at 10 emails. 
Please shut this up. From all I can see it's always the same content.

I also get OBS exceptions on e.g. :71 hourly :)

**Comment by jberry-suse** [comment]
This is due to the build hash that was added to allow for more aggressive skipping. While the target project is rebuilding after a round of accepts the hash will constantly change and thus the comments will be updated with new hash. A trade-off and based on the fact that we don't have a better mechanism than a comment to present/store this information.

The hash could be moved to a different location or perhaps only updated when the project is done building. That would mean one comment per accept round. Moving to staging psuedometa could be a solution, but adds a bit of complication to check both locations, but certainly doable.

The previous implementation would review all each loop and only post if comment differed, which was more work on repo-checker end, but less comments. What we really want is a notification flag to comment API, but short of that moving to psuedometa might be best bet.

**Comment by lnussel** [comment]
A trick that was used in some bot previously was to not update the comments but the review message. I think it works by setting the to repo-checker again (actually a noop as review is on repochecker already) and pass a message. That message is not sent by default.

**Comment by coolo** [comment]
you have to use change reviewstate from new to new to update the review comment. But please use human readable format there.

**Comment by jberry-suse** [comment]
I am not sure that's a comparable use-case since the messages would changes as well. Storing state information in the review history sounds like an even greater abuse. If anything, I'll likely change `repo-checker` to only update comment if either changes or target project is published and hash changed. That would seem to handle the cases desired.

**Comment by coolo** [comment]
I talked with @hennevogel and @ChrisBr yesterday about the problem in general. And OBS team favors generic 'status' reports from bots.

As those would still leave the question on when to send notifications, we agreed that we still need a flag in both comments and the reports on if there should be notifications.
