### ISSUE TITLE
factory-repo-checker: add comment if check is delayed

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#482]
the factory-repo-checker currently only changes the review if it couldn't approve the request. There are no notifications for that kind of events. factory-repo-checker should therefore add an obs comment if it couldn't approve a request for let's say 24 hours.

**Comment by jberry-suse** [comment]
Assume this is in reference to `checkrepo.py` and possibly `is_buildsuccess()` calls to `change_review_state(..., 'new', ...)`? It would seem handy to use #684, but if this is the code in question it does not run as a ReviewBot.

**Comment by lnussel** [comment]
osc-check_repo.py, yes. It uses change_review_state to update the comment in the request. That is intentional at first as does not generate a notification for most users as by default users are not subscribed to that kind of message. After some time it would be handy to generate a notification though so people start looking.
It makes sense to port repochecker to reviewbot too I guess.

**Comment by nilxam** [comment]
this will just annoying people if keep commenting... repochecker checks the group, so actually it don't know which *request* causes the problem blocked this group moving forward, if you do this then it does meaning repochecker commenting on all un-accepted requests in this group even the request unrelated to the problem in that group. this is exactly the case why we need  human keeps an eye on that.

**Comment by lnussel** [comment]
yes, the trick would be to find a balance between not becoming annoying and not commenting at all. That's why I thought about putting some timeout before commenting. If we don't let the bot comment at all, package maintainers will not learn about the problems, ie resolving them always stays on our shoulders.

**Comment by jberry-suse** [comment]
In the same fashion that the devel reminders check comment age before making another the delay or repeat delay should be feasible. While I'm in the code for #837 would be a convenient time to implement this, but we need some sort of decision.

Only comment in case of fail seems to be the idea since otherwise there is nothing to be done by the submitter.

In case of fail, there are likely two likely points for constraints.

1. Age of request
2. Delta since staged

At least for Leap waiting for `2` will likely need to be a requirement in the case of things like SLE requests although those will be by `leaper` and comments may not be relevant. Either way it seems best to wait for a request to be staged if it is not outright declined.

Likely once delta since last staged is `> 12` hours? or some number? Someone more familiar with failures in Factory would likely answer better.

On the other hand @nilxam comment about groups seems to make sense in that if the review is based on staging groups it may be related to any request in the group. Then one might say it would be better to post the comment on the project similar to the comment bot regarding build failures.

If so the likely path is waiting for build completion in staging project before posting comment. Same as `leaper` check if comment is similar first and if not either always update or have repeat delay.

Thoughts?

**Comment by coolo** [comment]
why not comment into the staging project? I don't need 19 comment emails if my staging project with 19 perl packages misses one dependency

**Comment by coolo** [comment]
and we already have a comment in the staging project - so extending this with the repochecker result seems appropriate.

**Comment by jberry-suse** [comment]
My thoughts exactly.
