### ISSUE TITLE
staging ignore command needs to use request finder

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#715]
the ignore command expects actual request numbers whereas other command also accept package names

**Comment by jberry-suse** [comment]
Part of the original thinking behind not doing this was to ensure that the request ID was always used rather than the package name and to make that clear to the user. For convenience it could use the finder and still store the request ID, but need to make it clear that once a request supersedes the new one will not be ignored by design.

If it seems like evaluating the package name into the request ID will still be clear I can go ahead and make this happen.
