### ISSUE TITLE
don't hardcode architectures in repochecker

### ISSUE THREAD

**Issue by lnussel** [openSUSE/osc-plugin-factory#764]
Repochecker currently hardcodes i586 and x86_64 as architectures. It needs to look at what the target actually has to determine what to require in the source project. Maybe abichecker could give some hints:
https://github.com/openSUSE/osc-plugin-factory/blob/master/abichecker/abichecker.py#L908

**Comment by nilxam** [comment]
Repochecker not just hardcoded that in one place, which one you're referencing to abichecker? or all?

**Comment by lnussel** [comment]
all places have to be fixed

**Comment by jberry-suse** [comment]
Some code sharing would have been nice rather then loads of copy/paste.

I assume the end goal here is to simply ensure there is a successful build in one of the target architectures of the target project. That seems to be what abichecker is doing.

**Comment by jberry-suse** [comment]
Made some progress. I have the list of architectures being read from main project and utilized in a number of places. The biggest issue seems to be the code previously assumed that a package had to have builds enabled for all considered archs (ie i586 and x86_64) whereas Leap has both enabled, but any project that build against Leap only have x86_64. With some tweaks I can get the check to pass, but need to know what is the desired requirement. Potentially only require that at least one of the considered archs if provided and that the package builds (or is excluded) in all applicable archs included in that repo, but this would not require them for Factory. Otherwise, given the setup of Leap will likely need some sort of hard coded map or somesuch.
