### ISSUE TITLE
osc staging: implement 'no locking needed' for some commands

### ISSUE THREAD

**Issue by DimStar77** [openSUSE/osc-plugin-factory#886]
There are a number of commands that do not modify the setup of stagings at all and that only are used to read information. Those commands should

a) be able to run even if somebody else has a lock
b) not lock the project, so others can run stagnig plugin without issues

The commands coming to mind are

* acheck
* check
* frozenage

**Comment by jberry-suse** [comment]
Potentially, `list` without `--supersede` and `adi` with some code tweaks, but that may be more work than worth.

Just a matter of if done by `OBSLock` or a not properties that is set from `osc-staging.py` when one of those commands matches. The latter probably makes more sense since `OBSlock` currently has virtual no knowledge about commands.
