### ISSUE TITLE
staging-bot should group request to adi staging per the devel project  on TW

### ISSUE THREAD

**Issue by nilxam** [openSUSE/osc-plugin-factory#947]
The origin default logic of TW adi staging is grouping request from the same devel project to an adi staging in one go, however we see staging-bot does not did that as our expected.

eg. https://build.opensuse.org/project/show/openSUSE:Factory:Staging:adi:15

<pre>
Staging Bot staging-bot wrote 2 days ago

Requests (dashboard):

    request#503055 for package python3-hl7apy submitted by @DocB
    request#503058 for package ghc-sibe submitted by @psimons
</pre>

or we should adjust the parameter for staging-bot?

**Comment by jberry-suse** [comment]
The behavior has not changed in regard to grouping by devel project. My understanding was the expected invocation for TW was:

```
osc staging adi
```

with no extra flags. The `staging-bot` currently runs with `osc staging adi --by-develproject`. I had intended to make this conditional when enabled for Factory, but looks like I never did. In practice it should never make a difference except when new packages are submitted as in the case you are referencing. Both packages are new and thus do not have a devel project in the sense that the queries to find a devel will return nothing.

Two solutions:

1) change the invocation for Factory to not include the `--by-develproject`
2) change the devel lookup to fallback to source project for new packages or lacking devel target

The second option seems preferable since this works nicely for Leap as well when new packages are submitted.

Thoughts?

**Comment by jberry-suse** [comment]
In fact option 2 is also better since it works for ring packages as well and the strategies applied to them.

**Comment by DimStar77** [comment]
Indeed, option 2 sounds reasonable - as the source project will automatically become the devel project afterwards.
